title: My Blog
author: xbilin2
email: blin_8991@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Everything is awesome.

# social links
github_username:  xbilin2

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
